name: predpoison
channels:
  - defaults
dependencies:
  - python=3.7.16
  - numpy>=1.18.1
  - pytorch
  - torchvision>=0.6.0
  - pillow>=7.0.0
  - setuptools>=46.1.3
  - tqdm
  - pip:
    - pretrainedmodels
    - matplotlib
